### ISSUE TITLE
Allow choice between Argon2i, Argon2d and Argon2id

### ISSUE THREAD

**Issue by Atulin** [scottbrady91/ScottBrady91.AspNetCore.Identity.Argon2PasswordHasher#1]

**Comment by scottbrady91** [comment]
This wasn't as easy as I was hoping it would be. Looks like the only option using libsodium is to move to [ArgonHashBinary](https://github.com/tabrath/libsodium-core/blob/master/src/Sodium.Core/PasswordHash.cs#L165) which seems to use a different format.

Seeing as libsodium now uses Argon2id by default and that is the [recommended version](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-argon2-12), do you see any reason to support all versions?

**Comment by Atulin** [comment]
No, I don't think there's a reason, if adding this functionality would be too bothersome. It's more of a nice-to-have thing, but hardly necessary.

**Comment by scottbrady91** [comment]
Okay, I'll close for now then. If anyone has a burning requirement for Argon2i or Argon2d then let me know 🙂
