### ISSUE TITLE
Trailing 0 characters cause an issue when storing to PostgreSQL

### ISSUE THREAD

**Issue by roji** [scottbrady91/ScottBrady91.AspNetCore.Identity.Argon2PasswordHasher#2]
In https://github.com/npgsql/efcore.pg/issues/1069, a project using this hasher attempted to store the results into PostgreSQL and failed, because the hashed password has trailing ASCII-0 characters; PostgreSQL does not support ASCII zeros in strings. I'm not sure if it makes sense to strip these, or pad with spaces instead - just informing you of this problem.

**Comment by scottbrady91** [comment]
Thanks for reporting. I've updated the dependencies responsible for this. If that doesn't work, I'll have to v2 this library and take control of the formatting myself.
